export const data = [
    {
        "name": "Camiseta 1",
        "url": "/images/photo1.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 2",
        "url": "/images/photo2.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 3",
        "url": "/images/photo3.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 4",
        "url": "/images/photo4.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 5",
        "url": "/images/photo5.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 6",
        "url": "/images/photo6.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 7",
        "url": "/images/photo7.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 8",
        "url": "/images/photo8.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
    {
        "name": "Camiseta 9",
        "url": "/images/photo9.jpeg",
        "description": "tela fria",
        "date": "2023-06-20",
        "type": "image/jpeg",
    },
]